version: '3.5'
services:
  ui:
    command: sh -c "npm install && npm run serve"
    restart: 'unless-stopped'
    ports:
      - '8033:8033'
  api:
    ports:
      - '5033:5000'
    environment:
      - USE_DEV_SERVER=True
      - DJANGO_SETTINGS_MODULE=svip_server.settings.development
  db:
    ports:
      - '30432:5432' # dev access port
  local_uta:
    ports:
      - '15032:5432'
  redis:
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'