version: '3.5'

volumes:
  svip_pgdata:
  seqrepo:
  web_root:
services:
  ui:
    build: ./svip-o-vue
    hostname: ui
    volumes:
      - ./svip-o-vue:/app:delegated
      - web_root:/web_root
      # allows the root git repo to be accessed in the container, which
      # lets GitRevisionPlugin tag each build with its commit hash, branch, etc.
      - .git:/app/.git:delegated,ro
    command: bash -c "npx browserslist@latest --update-db && npm ci && npm run build && rm -rf /web_root/* && cp -R /app/dist/* /web_root/"
    env_file:
      - .env
    depends_on:
      - api
    restart: 'no'
  api:
    build: ./svip_api
    hostname: api
    volumes:
      - ./svip_api:/app
      - ./svip_api/api/static:/vol/web/static:z
      - '/usr/local/share/seqrepo:/usr/local/share/seqrepo'
    depends_on:
      - db
      - redis
      - local_uta
    environment:
      - UTA_DB_URL=postgresql://anonymous@local_uta/uta/uta_20171026
      - HGVS_SEQREPO_DIR=/usr/local/share/seqrepo/latest
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
  db:
    image: 'postgres:11.1'
    hostname: db
    shm_size: '2gb'
    restart: unless-stopped
    command: -c 'max_wal_size=2GB'
    volumes:
      - 'svip_pgdata:/var/lib/postgresql/data'
      - ./svip_db_backups:/backups
      - ./service_config/postgres:/docker-entrypoint-initdb.d
    env_file:
      - .env
  local_uta:
    # image: biocommons/uta:uta_20190928
    image: biocommons/uta:uta_20171026
    hostname: local_uta
    restart: unless-stopped
    volumes:
      - '/usr/local/share/seqrepo:/usr/local/share/seqrepo'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: 'redis:alpine'
    hostname: redis
    restart: unless-stopped
    env_file:
      - .env
    
