version: "3.5"

volumes:
  vep_data:

services:
  harvester:
    build: ./g2p-aggregator/harvester
    working_dir: /app
    environment:
      - BIOONTOLOGY_API_KEY
      - ONCOKB_API_KEY
      - POSTGRES_HOST=db
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - UTA_DB_URL=postgresql://anonymous@local_uta/uta/uta_20171026
      - HGVS_SEQREPO_DIR=/usr/local/share/seqrepo/latest
    volumes:
      - "./g2p-aggregator/harvester:/app"
      - "./g2p-aggregator/data:/data"
      - "./outputs:/output"
      - "/usr/local/share/seqrepo:/usr/local/share/seqrepo"
      - "vep_data:/opt/data"
    depends_on:
      - db
      - local_uta
