# Generated by Django 2.1.3 on 2018-11-22 14:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrez_id', models.BigIntegerField(db_index=True, unique=True)),
                ('ensembl_gene_id', models.CharField(db_index=True, max_length=20)),
                ('symbol', models.CharField(db_index=True, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Variant Name')),
                ('description', models.TextField(db_index=True, null=True)),
                ('biomarker_type', models.CharField(max_length=30)),
                ('so_hierarchy', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), default=list, size=None, verbose_name='Hierarchy of SO IDs')),
                ('soid', models.CharField(default='', max_length=15, verbose_name='Sequence Ontology ID')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Gene')),
            ],
        ),
    ]
