# Generated by Django 2.1.3 on 2018-11-22 15:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181122_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='sources',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='variant',
            name='sources',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
