# Generated by Django 2.1.3 on 2018-11-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181122_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='soid',
            field=models.CharField(default='', max_length=15, null=True, verbose_name='Sequence Ontology ID'),
        ),
    ]
