# Generated by Django 2.1.3 on 2018-11-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181122_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='name',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Variant Name'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['gene', 'name'], name='api_variant_gene_id_9b7898_idx'),
        ),
    ]
