# Generated by Django 2.1.3 on 2018-11-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181123_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='so_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='biomarker_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
