# Generated by Django 2.1.3 on 2018-11-28 07:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181123_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
