# Generated by Django 2.1.3 on 2018-11-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_variant_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='source_url',
            field=models.TextField(null=True),
        ),
    ]
