# Generated by Django 2.1.3 on 2018-11-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_variant_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='name',
            field=models.CharField(db_index=True, max_length=120, verbose_name='Variant Name'),
        ),
    ]
