# Generated by Django 2.1.3 on 2018-11-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_association_environmentalcontext_evidence_phenotype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentalcontext',
            name='description',
            field=models.TextField(default='n/a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='environmentalcontext',
            name='source',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalcontext',
            name='usan_stem',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
