# Generated by Django 2.1.3 on 2018-11-30 08:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20181129_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='payload',
        ),
        migrations.AddField(
            model_name='association',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='association',
            name='source',
            field=models.CharField(default='oncokb', max_length=30),
            preserve_default=False,
        ),
    ]
