# Generated by Django 2.1.3 on 2018-11-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20181130_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='source_url',
        ),
        migrations.AddField(
            model_name='association',
            name='source_url',
            field=models.TextField(null=True),
        ),
    ]
