# Generated by Django 2.1.3 on 2018-12-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20181130_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentalcontext',
            name='envcontext_id',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
