# Generated by Django 2.1.3 on 2019-01-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20181214_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='uniprot_id',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
