# Generated by Django 2.1.3 on 2019-01-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_gene_uniprot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='chromosome',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='end_pos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='hgvs_c',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='hgvs_p',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='reference_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='start_pos',
            field=models.IntegerField(null=True),
        ),
    ]
