# Generated by Django 2.1.3 on 2019-01-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190116_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='hgvs_g',
            field=models.TextField(null=True),
        ),
    ]
