# Generated by Django 2.1.3 on 2019-01-17 14:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_variant_hgvs_g'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene',
            name='uniprot_id',
        ),
        migrations.AddField(
            model_name='gene',
            name='uniprot_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None, verbose_name='UniProt IDs'),
        ),
    ]
