# Generated by Django 2.1.3 on 2019-01-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190117_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
