# Generated by Django 2.1.3 on 2019-01-23 12:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_gene_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='dbsnp_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None, verbose_name='UniProt IDs'),
        ),
        migrations.AddField(
            model_name='variant',
            name='myvariant_h19',
            field=models.TextField(null=True, verbose_name='=MyVariant.info URL (hg19)'),
        ),
    ]
