# Generated by Django 2.1.3 on 2019-01-25 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20190123_1307'),
    ]

    operations = [
        migrations.RunSQL(
            sql="create index api_variant_name_lc on api_variant (lower(name))",
            reverse_sql="drop index api_variant_name_lc"
        )
    ]
