# Generated by Django 2.1.3 on 2019-01-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20190125_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='drug_labels',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='evidence_label',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='evidence_level',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='response_type',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='source',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='environmentalcontext',
            name='envcontext_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='environmentalcontext',
            name='source',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='environmentalcontext',
            name='term',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='environmentalcontext',
            name='usan_stem',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='evidenceType_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='evidenceType_sourceName',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='type',
            field=models.TextField(choices=[('predictive', 'Predictive'), ('prognostic', 'Prognostic'), ('predisposing', 'Predisposing'), ('diagnostic', 'Diagnostic')]),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='family',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='pheno_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='source',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='term',
            field=models.TextField(null=True),
        ),
    ]
