# Generated by Django 2.1.3 on 2019-01-25 12:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20190125_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], null=True, size=None),
        ),
        migrations.AddField(
            model_name='gene',
            name='prev_symbols',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], null=True, size=None),
        ),
    ]
