# Generated by Django 2.1.3 on 2019-01-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20190125_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentalcontext',
            name='term',
            field=models.TextField(null=True),
        ),
    ]
