# Generated by Django 2.1.3 on 2019-01-28 15:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20190125_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='mv_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
