# Generated by Django 2.1.3 on 2019-02-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_variant_mv_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='drug_interaction_type',
            field=models.TextField(null=True),
        ),
    ]
