# Generated by Django 2.1.3 on 2019-02-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_association_drug_interaction_type'),
    ]

    operations = [
        migrations.RunSQL("""
        -- array_distinct declaration
        create or replace function array_distinct(anyarray) returns anyarray
          immutable
          language sql
        as
        $$
        SELECT array_agg(DISTINCT x) FROM unnest($1) t(x);
        $$;
        alter function array_distinct(anyarray) owner to postgres;
        """, reverse_sql="""
        drop function if exists array_distinct;
        """)
    ]
