# Generated by Django 2.1.3 on 2019-03-05 11:36

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20190208_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantInSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_url', models.TextField(null=True, verbose_name="Variant's URL for this source")),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Source-specific extra data')),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='display_name',
            field=models.TextField(default='n/a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='association',
            name='source_link',
            field=models.TextField(null=True, verbose_name="URL of the association's entry in the source"),
        ),
        migrations.AlterField(
            model_name='association',
            name='source_url',
            field=models.TextField(null=True, verbose_name="URL of the variant's entry in the source"),
        ),
        migrations.AlterField(
            model_name='gene',
            name='sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None, verbose_name='Sources'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None, verbose_name='Sources'),
        ),
        migrations.AddField(
            model_name='variantinsource',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Source'),
        ),
        migrations.AddField(
            model_name='variantinsource',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Variant'),
        ),
        migrations.AddField(
            model_name='association',
            name='variant_in_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.VariantInSource'),
        ),
    ]
