# Generated by Django 2.1.3 on 2019-03-05 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20190305_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='variant_in_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.VariantInSource'),
        ),
        migrations.AlterUniqueTogether(
            name='variantinsource',
            unique_together={('variant', 'source')},
        ),
    ]
