# Generated by Django 2.1.3 on 2019-03-05 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_populate_sources__and__var_in_source'),
    ]

    operations = [
        # ensure that variant_in_source is non-null now that it's populated
        migrations.AlterField(
            model_name='association',
            name='variant_in_source',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to='api.VariantInSource'),
        ),
    ]
