# Generated by Django 2.1.3 on 2019-03-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_set_var_in_source__non-null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='gene',
        ),
        migrations.RemoveField(
            model_name='association',
            name='variant',
        ),
    ]
