# Generated by Django 2.1.3 on 2019-03-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20190308_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='evidence_label',
        ),
        migrations.AddField(
            model_name='association',
            name='evidence_direction',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='evidence_type',
            field=models.TextField(null=True),
        ),
    ]
