# Generated by Django 2.1.3 on 2019-03-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20190308_1327'),
    ]

    operations = [
        migrations.RunSQL("""
        update api_association A set evidence_type=(
            select distinct type from api_evidence where association_id=A.id
        )
        """)
    ]
