# Generated by Django 2.1.3 on 2019-03-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_ev_type_to_assoc_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='description',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='type',
        ),
        migrations.AlterField(
            model_name='association',
            name='evidence_type',
            field=models.TextField(choices=[('predictive', 'Predictive'), ('prognostic', 'Prognostic'), ('predisposing', 'Predisposing'), ('diagnostic', 'Diagnostic')], null=True),
        ),
    ]
