# Generated by Django 2.1.3 on 2019-03-15 10:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20190308_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='SVIPVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Variant')),
            ],
        ),
    ]
