# Generated by Django 2.1.3 on 2019-03-15 10:28
import json
import os
import sys

from django.db import migrations

import api

APP_DIR = os.path.dirname(api.__file__)
SVIP_VARS_JSON = os.path.join(APP_DIR, "fixtures", "svip_variants.json")


def create_svipvariants(apps, schema_editor):
    # loads variant info from SVIP mock data file into the db
    with open(SVIP_VARS_JSON) as fp:
        svip_variants = json.load(fp)

        Variant = apps.get_model('api', 'Variant')
        SVIPVariant = apps.get_model('api', 'SVIPVariant')
        SVIPVariant.objects.all().delete()

        for s in svip_variants:
            try:
                target_variant = Variant.objects.get(
                    gene__symbol=s['gene_name'],
                    name=s['variant_name']
                )
                candidate = SVIPVariant(
                    variant=target_variant,
                    data=s
                )
                candidate.save()
            except Variant.DoesNotExist:
                print(
                    "Couldn't find corresponding variant w/gene and name '%s %s', skipping..." %
                    (s['gene_name'], s['variant_name']), file=sys.stderr
                )


def drop_svipvariants(apps, schema_editor):
    SVIPVariant = apps.get_model('api', 'SVIPVariant')
    SVIPVariant.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_svipvariant'),
    ]

    operations = [
        migrations.RunPython(create_svipvariants, reverse_code=drop_svipvariants)
    ]
