# Generated by Django 2.1.3 on 2019-03-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_populate_svipvariant_from_mockdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='hgvs_c',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='hgvs_g',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='hgvs_p',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='so_name',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
