# Generated by Django 2.1.3 on 2019-04-11 11:06

from django.db import migrations, models
import django_db_cascade.deletions
import django_db_cascade.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20190315_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='variant_in_source',
            field=django_db_cascade.fields.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.VariantInSource'),
        ),
        migrations.AlterField(
            model_name='environmentalcontext',
            name='association',
            field=django_db_cascade.fields.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.Association'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='association',
            field=django_db_cascade.fields.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.Association'),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='association',
            field=django_db_cascade.fields.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.Association'),
        ),
        migrations.AlterField(
            model_name='svipvariant',
            name='variant',
            field=django_db_cascade.fields.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.Variant'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='gene',
            field=django_db_cascade.fields.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.Gene'),
        ),
        migrations.AlterField(
            model_name='variantinsource',
            name='source',
            field=django_db_cascade.fields.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.Source'),
        ),
        migrations.AlterField(
            model_name='variantinsource',
            name='variant',
            field=django_db_cascade.fields.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.Variant'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['gene', 'name', 'hgvs_c'], name='api_variant_gene_id_fcd755_idx'),
        ),
    ]
