# Generated by Django 2.1.3 on 2019-04-12 07:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20190411_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='crawl_status',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='crawl_status',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
