# Generated by Django 2.1.3 on 2019-04-25 13:15

from django.db import migrations, models
import django_db_cascade.deletions
import django_db_cascade.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20190412_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurationEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.TextField(verbose_name='Disease')),
                ('type_of_evidence', models.TextField(verbose_name='Type of evidence')),
                ('drug', models.TextField(verbose_name='Drug')),
                ('effect', models.TextField(verbose_name='Effect')),
                ('tier_level_criteria', models.TextField(verbose_name='Tier level Criteria')),
                ('summary', models.TextField(verbose_name='Summary')),
                ('support', models.TextField(verbose_name='Support')),
                ('references', models.TextField(verbose_name='References')),
            ],
            options={
                'db_table': 'svip_curationentry',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.TextField(verbose_name='Disease')),
                ('sample_id', models.TextField(verbose_name='Sample ID')),
                ('year_of_birth', models.TextField(verbose_name='Year of birth')),
                ('gender', models.TextField(verbose_name='Gender')),
                ('hospital', models.TextField(verbose_name='Hospital')),
                ('medical_service', models.TextField(verbose_name='Medical service')),
                ('provider_annotation', models.TextField(verbose_name='Provider annotation')),
                ('sample_tissue', models.TextField(verbose_name='Sample Tissue')),
                ('tumor_purity', models.TextField(verbose_name='Tumor purity')),
                ('tnm_stage', models.TextField(verbose_name='TNM stage')),
                ('sample_type', models.TextField(verbose_name='Sample type')),
                ('sample_site', models.TextField(verbose_name='Sample site')),
                ('specimen_type', models.TextField(verbose_name='Specimen Type')),
                ('sequencing_date', models.TextField(verbose_name='Sequencing date')),
                ('panel', models.TextField(verbose_name='Panel')),
                ('coverage', models.TextField(verbose_name='Coverage')),
                ('calling_strategy', models.TextField(verbose_name='Calling strategy')),
                ('caller', models.TextField(verbose_name='Caller')),
                ('aligner', models.TextField(verbose_name='Aligner')),
                ('software', models.TextField(verbose_name='Software')),
                ('software_version', models.TextField(verbose_name='Software version')),
                ('platform', models.TextField(verbose_name='Platform')),
                ('contact', models.TextField(verbose_name='Contact')),
            ],
            options={
                'db_table': 'svip_sample',
            },
        ),
        migrations.RenameModel(
            old_name='SVIPVariant',
            new_name='VariantInSVIP',
        ),
        migrations.AddField(
            model_name='sample',
            name='svip_variant',
            field=django_db_cascade.fields.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.VariantInSVIP'),
        ),
        migrations.AddField(
            model_name='curationentry',
            name='svip_variant',
            field=django_db_cascade.fields.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.VariantInSVIP'),
        ),
    ]
