# Generated by Django 2.1.3 on 2019-05-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20190516_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='confidence_score',
            new_name='score',
        ),
    ]
