# Generated by Django 2.1.3 on 2019-05-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20190517_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='curationentry',
            name='mutation_origin',
            field=models.TextField(default='Somatic', verbose_name='Mutation Origin'),
        ),
        migrations.AlterField(
            model_name='curationentry',
            name='summary',
            field=models.TextField(verbose_name='Complementary information'),
        ),
    ]
