# Generated by Django 2.2.4 on 2019-09-03 07:18

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_create_test_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollapsedAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.TextField(blank=True, null=True)),
                ('evidence_type', models.TextField(blank=True, null=True)),
                ('evidence_direction', models.TextField(blank=True, null=True)),
                ('clinical_significance', models.TextField(blank=True, null=True)),
                ('drug_labels', models.TextField(blank=True, null=True)),
                ('contexts', models.TextField(blank=True, null=True)),
                ('evidence_levels', models.TextField(blank=True, null=True)),
                ('publications', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Publication URLs')),
                ('children', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('collapsed_count', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_collapsed_associations',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='association',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Association-specific extra data'),
        ),
    ]
