# Generated by Django 2.2.4 on 2019-10-18 12:32

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import django_db_cascade.deletions
from django.contrib.auth import get_user_model


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0057_auto_20190903_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='curationentry',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='curationentry',
            name='owner',
            field=models.ForeignKey(
                default=None,
                on_delete=django_db_cascade.deletions.DB_CASCADE, to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curationentry',
            name='status',
            field=models.TextField(choices=[('draft', 'draft'), ('saved', 'saved'), ('submitted', 'submitted'), ('reviewed', 'reviewed')], default='draft', verbose_name='Curation Status'),
        ),
    ]
