# Generated by Django 2.2.4 on 2019-10-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20191018_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.TextField()),
                ('medicine_name', models.TextField()),
                ('active_substance', models.TextField()),
                ('target_area', models.TextField()),
                ('product_number', models.TextField()),
                ('atc_code', models.TextField(null=True)),
            ],
        ),
    ]
