# Generated by Django 2.2.4 on 2019-10-18 15:14
import os
from csv import DictReader

from django.db import migrations

import api


APP_DIR = os.path.dirname(api.__file__)
DRUGS_TSV = os.path.join(APP_DIR, "fixtures", "drugs.tsv")


def create_drugs(apps, schema_editor):
    with open(DRUGS_TSV) as fp:
        drugs = DictReader(fp, dialect='excel-tab')

        Drug = apps.get_model('api', 'Drug')
        Drug.objects.all().delete()

        for s in drugs:
            # FIXME: yes, i realize this is silly, but we're getting some silly results
            candidate = Drug(
                common_name=s['common_name'],
                medicine_name=s['medicine_name'],
                active_substance=s['active_substance'],
                target_area=s['target_area'],
                product_number=s['product_number'],
                atc_code=s['atc_code']
            )
            candidate.save()


def drop_drugs(apps, schema_editor):
    Drug = apps.get_model('api', 'Drug')
    Drug.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_drug'),
    ]

    operations = [
        migrations.RunPython(create_drugs, reverse_code=drop_drugs)
    ]
