# Generated by Django 2.2.4 on 2019-10-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_populate_drugs'),
    ]

    operations = [
        migrations.RenameModel('Disease', 'DiseaseInSVIP'),
        migrations.AlterModelTable(
            name='diseaseinsvip',
            table='svip_diseaseinsvip',
        ),
    ]
