# Generated by Django 2.2.4 on 2019-10-23 11:51

from django.db import migrations, models
import django_db_cascade.deletions
import django_db_cascade.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_rename_disease_to_DiSVIP'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('icdo_code', models.TextField(null=True)),
            ],
        )
    ]
