# Generated by Django 2.2.4 on 2019-10-24 07:20

from django.db import migrations, models
import django_db_cascade.deletions
import django_db_cascade.fields


def add_variants(apps, schema_editor):
    CurationEntry = apps.get_model('api', 'CurationEntry')

    for entry in CurationEntry.objects.all():
        entry.variants.add(entry.variant)


def remove_variants(apps, schema_editor):
    CurationEntry = apps.get_model('api', 'CurationEntry')

    for entry in CurationEntry.objects.all():
        # this is destructive, but hey, you wanted a reverse migration from many to one...
        entry.variant = entry.variants.first()
        entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20191023_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='curationentry',
            name='variants',
            field=models.ManyToManyField(to='api.Variant'),
        ),
        migrations.RunPython(
            code=add_variants, reverse_code=remove_variants
        ),
        migrations.RemoveField(
            model_name='curationentry',
            name='variant',
        ),
    ]
