# Generated by Django 2.2.4 on 2019-10-24 20:13

from django.db import migrations, models
import django_db_cascade.deletions
import django_db_cascade.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20191024_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curationentry',
            name='drug',
            field=models.TextField(null=True, verbose_name='Drug'),
        ),
        migrations.AlterField(
            model_name='curationentry',
            name='effect',
            field=models.TextField(null=True, verbose_name='Effect'),
        ),
        migrations.AlterField(
            model_name='curationentry',
            name='mutation_origin',
            field=models.TextField(default='Somatic', null=True, verbose_name='Mutation Origin'),
        ),
        migrations.AlterField(
            model_name='curationentry',
            name='references',
            field=models.TextField(null=True, verbose_name='References'),
        ),
        migrations.AlterField(
            model_name='curationentry',
            name='summary',
            field=models.TextField(null=True, verbose_name='Complementary information'),
        ),
        migrations.AlterField(
            model_name='curationentry',
            name='support',
            field=models.TextField(null=True, verbose_name='Support'),
        ),
        migrations.AlterField(
            model_name='curationentry',
            name='tier_level',
            field=models.TextField(null=True, verbose_name='Tier level'),
        ),
        migrations.AlterField(
            model_name='curationentry',
            name='tier_level_criteria',
            field=models.TextField(null=True, verbose_name='Tier level Criteria'),
        ),
        migrations.AlterField(
            model_name='curationentry',
            name='type_of_evidence',
            field=models.TextField(null=True, verbose_name='Type of evidence'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='disease_in_svip',
            field=django_db_cascade.fields.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.DiseaseInSVIP'),
        ),
    ]
