# Generated by Django 2.2.4 on 2019-10-24 20:29

from django.db import migrations, models
import django_db_cascade.deletions
import django_db_cascade.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_make_CE_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='icdo_code',
        ),
        migrations.AddField(
            model_name='disease',
            name='abbreviation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='localization',
            field=models.TextField(default='LUNG'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='morpho_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='snomed_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='snomed_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='topo_code',
            field=models.TextField(null=True),
        )
    ]
