# Generated by Django 2.2.4 on 2019-10-24 21:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django_db_cascade.deletions
import django_db_cascade.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_populate_diseases'),
    ]

    operations = [
        migrations.AddField(
            model_name='curationentry',
            name='annotations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='curationentry',
            name='comment',
            field=models.TextField(null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='curationentry',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
