# Generated by Django 2.2.4 on 2019-10-25 15:38

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_db_cascade.deletions
import django_db_cascade.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0070_add_CE_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curationentry',
            name='status',
            field=models.TextField(choices=[('draft', 'draft'), ('saved', 'saved'), ('submitted', 'submitted'), ('reviewed', 'reviewed')], db_index=True, default='draft', verbose_name='Curation Status'),
        ),
        migrations.CreateModel(
            name='HistoricalCurationEntry',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('type_of_evidence', models.TextField(null=True, verbose_name='Type of evidence')),
                ('drug', models.TextField(null=True, verbose_name='Drug')),
                ('effect', models.TextField(null=True, verbose_name='Effect')),
                ('tier_level_criteria', models.TextField(null=True, verbose_name='Tier level Criteria')),
                ('tier_level', models.TextField(null=True, verbose_name='Tier level')),
                ('mutation_origin', models.TextField(default='Somatic', null=True, verbose_name='Mutation Origin')),
                ('summary', models.TextField(null=True, verbose_name='Complementary information')),
                ('support', models.TextField(null=True, verbose_name='Support')),
                ('comment', models.TextField(null=True, verbose_name='Comment')),
                ('references', models.TextField(null=True, verbose_name='References')),
                ('annotations', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(blank=True, editable=False)),
                ('status', models.TextField(choices=[('draft', 'draft'), ('saved', 'saved'), ('submitted', 'submitted'), ('reviewed', 'reviewed')], db_index=True, default='draft', verbose_name='Curation Status')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('disease', django_db_cascade.fields.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Disease')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical curation entry',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
