# Generated by Django 2.2.4 on 2019-10-25 16:49

from django.db import migrations
import django_db_cascade.deletions
import django_db_cascade.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_track_CE_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcurationentry',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='historicalcurationentry',
            name='last_modified',
        )
    ]
