# Generated by Django 2.2.4 on 2019-10-28 10:48

from django.db import migrations, models
import django.utils.timezone
import django_db_cascade.deletions
import django_db_cascade.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_auto_20191025_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curationentry',
            name='created_on',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='curationentry',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        )
    ]
