# Generated by Django 2.2.4 on 2019-11-11 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_db_cascade.deletions
import django_db_cascade.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0073_add_CE_indices'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurationReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.TextField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('accepted', 'accepted')], db_index=True, default='pending', verbose_name='Review Status')),
                ('curation_entry', django_db_cascade.fields.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.CurationEntry')),
                ('reviewer', models.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'svip_curationreview',
            },
        ),
        migrations.CreateModel(
            name='CurationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('due_by', models.DateTimeField(db_index=True)),
                ('disease', django_db_cascade.fields.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.Disease')),
                ('requestor', models.ForeignKey(null=True, on_delete=django_db_cascade.deletions.DB_CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.Variant')),
            ],
            options={
                'db_table': 'svip_curationrequest',
            },
        ),
        migrations.AddField(
            model_name='curationentry',
            name='request',
            field=django_db_cascade.fields.ForeignKey(null=True, on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.CurationRequest'),
        ),
        migrations.AddField(
            model_name='historicalcurationentry',
            name='request',
            field=django_db_cascade.fields.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.CurationRequest'),
        ),
    ]
