# Generated by Django 2.2.4 on 2019-11-11 16:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_CE_request_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curationentry',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='historicalcurationentry',
            name='drug',
        ),
        migrations.AddField(
            model_name='curationentry',
            name='drugs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None, verbose_name='Drugs'),
        ),
        migrations.AddField(
            model_name='historicalcurationentry',
            name='drugs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None, verbose_name='Drugs'),
        ),
    ]
