# Generated by Django 2.2.4 on 2019-11-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_auto_20191111_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantCuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curationentry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CurationEntry')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Variant')),
            ],
            options={
                'db_table': 'svip_variantcuration',
            },
        ),
        migrations.AddField(
            model_name='curationentry',
            name='variants_new',
            field=models.ManyToManyField(related_name='variants_new', through='api.VariantCuration', to='api.Variant'),
        ),
    ]
