# Generated by Django 2.2.4 on 2019-11-18 09:59

from django.db import migrations


def attach_variants(apps, schema_editor):
    CurationEntry = apps.get_model('api', 'CurationEntry')
    VariantCuration = apps.get_model('api', 'VariantCuration')

    for ce in CurationEntry.objects.all():
        candidate = ce.extra_variants.first()
        if candidate:
            ce.variant = candidate
            ce.save()
            VariantCuration.objects.filter(curationentry=ce, variant=candidate).delete()
            ce.save()


def detach_variants(apps, schema_editor):
    CurationEntry = apps.get_model('api', 'CurationEntry')

    for ce in CurationEntry.objects.all():
        ce.extra_variants.add(ce.variant)
        ce.variant = None
        ce.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_auto_20191118_0935'),
    ]

    operations = [
        migrations.RunPython(
            code=attach_variants,
            reverse_code=detach_variants
        )
    ]
