# Generated by Django 2.2.4 on 2019-11-25 11:58

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import django_db_cascade.deletions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0081_auto_20191118_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('owner', models.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.Variant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
