# Generated by Django 2.2.4 on 2019-12-07 12:29

from django.conf import settings
from django.db import migrations, models
import django_db_cascade.deletions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0083_tagtype_varianttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='varianttag',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django_db_cascade.deletions.DB_CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
