# Generated by Django 2.2.4 on 2019-12-09 05:45

from django.db import migrations, models
import django_db_cascade.deletions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_varianttag_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantcomment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.VariantComment'),
        ),
    ]
