# Generated by Django 2.2.4 on 2020-01-10 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_variantcomment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varianttag',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='varianttag',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='varianttag',
            name='type',
        ),
        migrations.DeleteModel(
            name='TagType',
        ),
        migrations.DeleteModel(
            name='VariantTag',
        ),
    ]
