# Generated by Django 2.2.4 on 2020-01-20 16:01

from django.db import migrations, models
import django_db_cascade.deletions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_variantcomment_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantcuration',
            name='curationentry',
            field=models.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.CurationEntry'),
        ),
        migrations.AlterField(
            model_name='variantcuration',
            name='variant',
            field=models.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.Variant'),
        ),
    ]
