# Generated by Django 2.2.4 on 2020-01-22 09:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_auto_20200120_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_on', models.DateTimeField(null=True)),
                ('status', models.TextField(choices=[('running', 'running'), ('success', 'success'), ('failure', 'failure')], default='running')),
                ('output', models.TextField(null=True)),
                ('stats', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
    ]
