# Generated by Django 2.2.4 on 2020-02-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_harvestrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='somatic_status',
            field=models.TextField(null=True),
        ),
    ]
