# Generated by Django 2.2.4 on 2020-05-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_variant_somatic_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantinsvip',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
