# Generated by Django 2.2.4 on 2020-05-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_historicalvariantinsvip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvariantinsvip',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variantinsvip',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
