# Generated by Django 2.2.4 on 2020-05-19 08:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_auto_20200513_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='curationentry',
            name='interactions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None, verbose_name='Interactions'),
        ),
        migrations.AddField(
            model_name='historicalcurationentry',
            name='interactions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None, verbose_name='Interactions'),
        ),
    ]
