# Generated by Django 2.2.4 on 2020-06-26 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_auto_20200519_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curationentry',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='curationentry',
            name='status',
            field=models.TextField(choices=[('draft', 'draft'), ('saved', 'saved'), ('submitted', 'submitted'), ('unreviewed', 'unreviewed'), ('reviewed', 'reviewed')], db_index=True, default='draft', verbose_name='Curation Status'),
        ),
        migrations.AlterField(
            model_name='historicalcurationentry',
            name='status',
            field=models.TextField(choices=[('draft', 'draft'), ('saved', 'saved'), ('submitted', 'submitted'), ('unreviewed', 'unreviewed'), ('reviewed', 'reviewed')], db_index=True, default='draft', verbose_name='Curation Status'),
        ),
    ]
