# Generated by Django 2.2.4 on 2020-07-13 12:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone
import django_db_cascade.deletions
import django_db_cascade.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_auto_20200702_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='user_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='curationentry',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='curationentry',
            name='drugs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Drugs'),
        ),
        migrations.AlterField(
            model_name='curationentry',
            name='interactions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Interactions'),
        ),
        migrations.AlterField(
            model_name='curationentry',
            name='request',
            field=django_db_cascade.fields.ForeignKey(blank=True, null=True, on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.CurationRequest'),
        ),
        migrations.AlterField(
            model_name='curationentry',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Complementary information'),
        ),
        migrations.AlterField(
            model_name='curationentry',
            name='support',
            field=models.TextField(blank=True, null=True, verbose_name='Support'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='localization',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalcurationentry',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='historicalcurationentry',
            name='drugs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Drugs'),
        ),
        migrations.AlterField(
            model_name='historicalcurationentry',
            name='interactions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Interactions'),
        ),
        migrations.AlterField(
            model_name='historicalcurationentry',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Complementary information'),
        ),
        migrations.AlterField(
            model_name='historicalcurationentry',
            name='support',
            field=models.TextField(blank=True, null=True, verbose_name='Support'),
        ),
    ]
