# Generated by Django 2.2.4 on 2020-07-14 12:45

from django.db import migrations
import django.db.models.deletion
import django_db_cascade.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_auto_20200714_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curationentry',
            name='disease',
            field=django_db_cascade.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Disease'),
        ),
    ]
