# Generated by Django 2.2.4 on 2020-07-14 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_auto_20200714_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='user_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='curationentry',
            name='mutation_origin',
            field=models.TextField(blank=True, default='Somatic', null=True, verbose_name='Mutation Origin'),
        ),
        migrations.AlterField(
            model_name='historicalcurationentry',
            name='mutation_origin',
            field=models.TextField(blank=True, default='Somatic', null=True, verbose_name='Mutation Origin'),
        ),
    ]
