# Generated by Django 2.2.4 on 2020-07-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_auto_20200714_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='active_substance',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='medicine_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='product_number',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='target_area',
            field=models.TextField(null=True),
        ),
    ]
