# Generated by Django 2.2.4 on 2020-07-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_auto_20200714_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='curationentry',
            name='associated_mendelian_diseases',
            field=models.TextField(blank=True, null=True, verbose_name='Associated Mendelian Disease(s)'),
        ),
        migrations.AddField(
            model_name='historicalcurationentry',
            name='associated_mendelian_diseases',
            field=models.TextField(blank=True, null=True, verbose_name='Associated Mendelian Disease(s)'),
        ),
    ]
