# Generated by Django 2.2.4 on 2020-09-21 17:28

from django.db import migrations, models
import django.db.models.deletion
import django_db_cascade.deletions
import django_db_cascade.fields


class Migration(migrations.Migration):

    replaces = [('api', '0105_auto_20200920_1118'), ('api', '0106_auto_20200921_1224'), ('api', '0107_auto_20200921_1709')]

    dependencies = [
        ('api', '0104_auto_20200714_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaseinsvip',
            name='disease',
            field=django_db_cascade.fields.ForeignKey(null=True, on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.Disease'),
        ),
        migrations.AlterUniqueTogether(
            name='drug',
            unique_together={('common_name', 'user_created')},
        ),
        migrations.AlterUniqueTogether(
            name='disease',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='historicalvariantinsvip',
            name='variant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Variant'),
        ),
        migrations.AlterField(
            model_name='variantinsvip',
            name='variant',
            field=models.OneToOneField(on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.Variant'),
        ),
        migrations.AlterUniqueTogether(
            name='diseaseinsvip',
            unique_together={('svip_variant', 'disease')},
        ),
    ]
