# Generated by Django 2.2.4 on 2021-01-26 16:26

from django.db import connection, migrations

import os

def load_data_from_sql(filename):
    file_path = os.path.join(os.path.dirname(__file__), '../fixtures/', filename)
    sql_statement = open(file_path).read()
    with connection.cursor() as c:
        c.execute(sql_statement)

def change_disease_schema(apps, schema_editor):
    # first, we import the ICD-O tables (no effect on existing tables yet)
    load_data_from_sql('disease-schema-migration/dump_icd-o_tables.sql')

    # then, we modify api_disease's schema to just point to entries in the new ICD-O tables
    load_data_from_sql('disease-schema-migration/connection_to_api_disease.sql')

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_merge_sviptest_diseases'),
    ]

    operations = [
        migrations.RunPython(change_disease_schema, reverse_code=migrations.RunPython.noop)
    ]
