# Generated by Django 2.2.4 on 2021-02-24 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_apply_disease_schema_data'),
    ]

    operations = [
        migrations.RunSQL(
            """
            alter table icd_o_topo_api_disease add id serial;
            alter table icd_o_topo_api_disease add constraint icd_o_topo_api_disease_pk_2 primary key (id);
            """,
            reverse_sql="""alter table icd_o_topo_api_disease drop column id""")
    ]
