# Generated by Django 2.2.13 on 2021-06-23 04:15

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_db_cascade.fields


class Migration(migrations.Migration):

    replaces = [('api', '0109_submittedvariant_submittedvariantbatch'), ('api', '0110_auto_20210621_1645'), ('api', '0111_submittedvariant_submitted_for'), ('api', '0112_auto_20210621_2102'), ('api', '0113_auto_20210622_1825'), ('api', '0114_auto_20210622_2147'), ('api', '0115_auto_20210622_2151'), ('api', '0116_submittedvariant_canonical_only')]

    dependencies = [
        ('api', '0108_IcdOTopoApiDisease_add_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedVariantBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('vcf_body', models.TextField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'svip_submittedvariantbatch',
            },
        ),
        migrations.CreateModel(
            name='SubmittedVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('chromosome', models.TextField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), ('X', 'X'), ('Y', 'Y'), ('MT', 'MT')])),
                ('pos', models.IntegerField()),
                ('ref', models.TextField()),
                ('alt', models.TextField()),
                ('status', models.TextField(choices=[('pending', 'pending'), ('completed', 'completed'), ('error', 'error')], db_index=True, default='pending', verbose_name='Processing Status')),
                ('processed_on', models.DateTimeField(db_index=True, null=True)),
                ('error_msg', models.TextField(null=True)),
                ('batch', django_db_cascade.fields.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.SubmittedVariantBatch')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('curation_disease', models.ForeignKey(help_text='If for_curation_request is true, identifies the disease to which the new curation request should be associated', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Disease')),
                ('for_curation_request', models.BooleanField(default=False, help_text='If true, a curation request should be created when this submission is completed')),
                ('resulting_variants', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('requestor', models.TextField(help_text='If for_curation_request is true, identifies who asked for this variant to be submitted', null=True)),
                ('canonical_only', models.BooleanField(default=False, help_text='If true, only retain VEP variants marked canonical')),
            ],
            options={
                'db_table': 'svip_submittedvariant',
            },
        ),
        migrations.AlterField(
            model_name='curationrequest',
            name='due_by',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='curationrequest',
            name='requestor',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='curationrequest',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Variant'),
        ),
        migrations.AddField(
            model_name='curationrequest',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.SubmittedVariant'),
        ),
        migrations.AlterUniqueTogether(
            name='curationrequest',
            unique_together={('submission', 'variant')},
        ),
    ]
