# Generated by Django 2.2.13 on 2021-06-07 16:35

from django.db import migrations, models
import django_db_cascade.deletions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_summarycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarycomment',
            name='variant',
            field=models.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.VariantInSVIP'),
        ),
    ]
