# Generated by Django 2.2.13 on 2021-06-23 05:05

from django.db import migrations

def forward_op(apps, schema_editor):
    Source = apps.get_model('api', 'Source')

    if not Source.objects.filter(name='svip_queue').exists():
        Source.objects.create(name='svip_queue', display_name='SVIP Submissions')
    
def reverse_op(apps, schema_editor):
    Source = apps.get_model('api', 'Source')
    Source.objects.filter(name='svip_queue').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_submittedvariant_submittedvariantbatch_squashed_0116_submittedvariant_canonical_only'),
    ]

    operations = [
        migrations.RunPython(forward_op, reverse_code=reverse_op)
    ]
