# Generated by Django 2.2.13 on 2021-06-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_summarycomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summarycomment',
            name='user',
        ),
    ]
