# Generated by Django 2.2.13 on 2021-06-09 11:22

from django.conf import settings
from django.db import migrations, models
import django_db_cascade.deletions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0110_remove_summarycomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarycomment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django_db_cascade.deletions.DB_CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
