# Generated by Django 2.2.13 on 2021-06-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_auto_20210607_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarycomment',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
