# Generated by Django 2.2.13 on 2021-06-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_remove_summarycomment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summarycomment',
            name='variant',
        ),
    ]
