# Generated by Django 2.2.13 on 2021-06-07 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_summarycomment_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SummaryComment',
        ),
    ]
