# Generated by Django 2.2.13 on 2021-06-16 11:07

from django.db import migrations, models
import django_db_cascade.deletions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_auto_20210615_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarycomment',
            name='variant',
            field=models.ForeignKey(default=278, on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.Variant'),
        ),
    ]
