# Generated by Django 2.2.13 on 2021-06-17 20:40

from django.db import migrations, models
import django_db_cascade.deletions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_auto_20210616_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantDiseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.OneToOneField(on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.Variant')),
            ],
        ),
    ]
