# Generated by Django 2.2.13 on 2021-06-23 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_db_cascade.deletions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0119_variantdiseases'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurationAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Disease')),
                ('variant', models.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, related_name='curation_associations', to='api.Variant')),
            ],
        ),
        migrations.CreateModel(
            name='CurationEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_evidence', models.TextField(null=True)),
                ('annotated_effect', models.TextField(default='', null=True)),
                ('annotated_tier', models.TextField(default='', null=True)),
                ('association', models.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, related_name='curation_evidences', to='api.CurationAssociation')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_evidence', models.TextField(default='')),
                ('comment', models.TextField(default='')),
                ('disease', models.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.Disease')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.Variant')),
            ],
        ),
        migrations.AlterField(
            model_name='curationentry',
            name='variant',
            field=models.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, related_name='curations', to='api.Variant'),
        ),
        migrations.DeleteModel(
            name='VariantDiseases',
        ),
        migrations.AddField(
            model_name='curationentry',
            name='curation_evidence',
            field=models.ForeignKey(null=True, on_delete=django_db_cascade.deletions.DB_CASCADE, related_name='curation_entries', to='api.CurationEvidence'),
        ),
        migrations.AddField(
            model_name='historicalcurationentry',
            name='curation_evidence',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.CurationEvidence'),
        ),
    ]
