# Generated by Django 2.2.13 on 2021-06-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_variantdiseases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantdiseases',
            name='variant',
        ),
        migrations.AddField(
            model_name='variantdiseases',
            name='random_var',
            field=models.TextField(null=True),
        ),
    ]
