# Generated by Django 2.2.13 on 2021-06-25 07:11

from django.db import migrations, models
import django_db_cascade.deletions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_auto_20210625_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantinsvip',
            name='variant',
            field=models.OneToOneField(on_delete=django_db_cascade.deletions.DB_CASCADE, related_name='variantinsvip', to='api.Variant'),
        ),
    ]
