# Generated by Django 2.2.13 on 2021-06-17 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_auto_20210617_2046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariantDiseases',
        ),
    ]
