# Generated by Django 2.2.13 on 2021-06-18 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_db_cascade.deletions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0121_delete_variantdiseases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_evidence', models.TextField(default='')),
                ('comment', models.TextField(default='')),
                ('disease', models.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.Disease')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.Variant')),
            ],
        ),
    ]
