# Generated by Django 2.2.24 on 2021-06-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_auto_20210625_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='curationreview',
            name='annotated_effect',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='curationreview',
            name='annotated_tier',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='curationreview',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='curationevidence',
            name='annotated_effect',
            field=models.TextField(default='Not yet annotated', null=True),
        ),
        migrations.AlterField(
            model_name='curationevidence',
            name='annotated_tier',
            field=models.TextField(default='Not yet annotated', null=True),
        ),
    ]
