# Generated by Django 2.2.13 on 2021-06-23 09:47

from django.db import migrations, models
import django.db.models.deletion
import django_db_cascade.deletions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_auto_20210623_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='curationentry',
            name='curation_evidence',
            field=models.ForeignKey(null=True, on_delete=django_db_cascade.deletions.DB_CASCADE, related_name='curation_entries', to='api.CurationEvidence'),
        ),
        migrations.AddField(
            model_name='historicalcurationentry',
            name='curation_evidence',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.CurationEvidence'),
        ),
    ]
