# Generated by Django 2.2.13 on 2021-06-23 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_auto_20210623_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curationentry',
            name='curation_evidence',
        ),
        migrations.RemoveField(
            model_name='historicalcurationentry',
            name='curation_evidence',
        ),
    ]
