# Generated by Django 2.2.13 on 2021-06-21 12:55

from django.db import migrations, models
import django_db_cascade.deletions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_auto_20210621_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curationentry',
            name='variant',
            field=models.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, related_name='curations', to='api.Variant'),
        ),
        migrations.AlterField(
            model_name='curationrequest',
            name='variant',
            field=models.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.Variant'),
        ),
    ]
