# Generated by Django 2.2.24 on 2021-06-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_auto_20210629_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curationreview',
            name='annotated_effect',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curationreview',
            name='annotated_tier',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curationreview',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
