# Generated by Django 2.2.13 on 2021-06-23 12:54

from django.conf import settings
from django.db import migrations, models
import django_db_cascade.deletions
import django_db_cascade.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_auto_20210623_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curationreview',
            name='curation_entry',
        ),
        migrations.AddField(
            model_name='curationreview',
            name='curation_evidence',
            field=django_db_cascade.fields.ForeignKey(null=True, on_delete=django_db_cascade.deletions.DB_CASCADE, to='api.CurationEvidence'),
        ),
        migrations.AlterField(
            model_name='curationreview',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django_db_cascade.deletions.DB_CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
