# Generated by Django 2.2.24 on 2021-07-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_set_svip_queue_no_assocs'),
        ('api', '0124_auto_20210629_1322'),
    ]

    operations = [
    ]
