# Generated by Django 2.2.13 on 2021-06-22 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_curationassociation_curationevidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='curationentry',
            name='curation_evidences',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curation_entries', to='api.CurationEvidence'),
        ),
        migrations.AddField(
            model_name='historicalcurationentry',
            name='curation_evidences',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.CurationEvidence'),
        ),
        migrations.AlterField(
            model_name='curationevidence',
            name='type_of_evidence',
            field=models.TextField(null=True),
        ),
    ]
