# Generated by Django 2.2.13 on 2021-06-23 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_auto_20210622_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curationentry',
            name='curation_evidences',
        ),
        migrations.RemoveField(
            model_name='historicalcurationentry',
            name='curation_evidences',
        ),
    ]
