# Generated by Django 2.2.24 on 2021-07-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        #('api', '0128_auto_20210701_1704'),
        ('api', '0128_create_svip_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='curationevidence',
            name='drug',
            field=models.TextField(null=True),
        ),
    ]
