# Generated by Django 2.2.24 on 2021-07-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_curationevidence_drug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curationentry',
            name='curation_evidence',
        ),
        migrations.RemoveField(
            model_name='historicalcurationentry',
            name='curation_evidence',
        ),
        migrations.AddField(
            model_name='curationentry',
            name='curation_evidences',
            field=models.ManyToManyField(to='api.CurationEvidence'),
        ),
    ]
