# Generated by Django 2.2.13 on 2021-06-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_auto_20210623_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curationevidence',
            name='annotated_effect',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='curationevidence',
            name='annotated_tier',
            field=models.TextField(default='', null=True),
        ),
    ]
