# Generated by Django 2.2.24 on 2021-07-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_auto_20210702_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curationentry',
            name='curation_evidences',
            field=models.ManyToManyField(related_name='curation_entries', to='api.CurationEvidence'),
        ),
    ]
