# Generated by Django 2.2.13 on 2021-06-23 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_auto_20210623_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curationentry',
            old_name='curation_evidences',
            new_name='curation_evidence',
        ),
        migrations.RenameField(
            model_name='historicalcurationentry',
            old_name='curation_evidences',
            new_name='curation_evidence',
        ),
    ]
