# Generated by Django 2.2.24 on 2021-07-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_auto_20210713_1537'),
        ('api', '0005_auto_20181122_1647 copy'),
    ]

    operations = [
    ]
