# Generated by Django 2.2.24 on 2021-08-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0138_delete_review_objects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SIBAnnotation',
            new_name='SIBAnnotation1',
        ),
    ]
