# Generated by Django 2.2.24 on 2021-08-23 09:11

from django.db import migrations, models
import django_db_cascade.deletions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0140_auto_20210819_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIBAnnotation2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.TextField(default='Not yet annotated', null=True)),
                ('tier', models.TextField(default='Not yet annotated', null=True)),
                ('clinical_input', models.TextField(null=True)),
                ('evidence', models.OneToOneField(on_delete=django_db_cascade.deletions.DB_CASCADE, related_name='annotation2', to='api.CurationEvidence')),
            ],
        ),
    ]
