# Generated by Django 2.2.24 on 2021-10-07 10:29

from django.db import migrations, models
import django.db.models.deletion
import django_db_cascade.deletions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_summarydraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curationrequest',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curation_request', to='api.Variant'),
        ),
        migrations.CreateModel(
            name='VariantStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('variants', models.OneToOneField(on_delete=django_db_cascade.deletions.DB_CASCADE, related_name='status', to='api.Variant')),
            ],
        ),
    ]
