# Generated by Django 2.2.24 on 2021-10-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0143_auto_20211007_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantstatus',
            name='variants',
        ),
    ]
