# Generated by Django 2.2.24 on 2021-10-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0144_remove_variantstatus_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantstatus',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
