# Generated by Django 2.2.24 on 2021-10-08 03:43

from django.db import migrations, models
import django_db_cascade.deletions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0145_variantstatus_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django_db_cascade.deletions.DB_CASCADE, related_name='variants', to='api.VariantStatus'),
        ),
    ]
