# Generated by Django 2.2.24 on 2021-10-08 09:30

from django.conf import settings
from django.db import migrations, models
import django_db_cascade.deletions
import django_db_cascade.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0146_variant_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisedReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agree', models.BooleanField()),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('curation_evidence', django_db_cascade.fields.ForeignKey(null=True, on_delete=django_db_cascade.deletions.DB_CASCADE, related_name='revised_reviews', to='api.CurationEvidence')),
                ('reviewer', models.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
