# Generated by Django 2.2.24 on 2021-10-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0147_revisedreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='status',
        ),
        migrations.DeleteModel(
            name='VariantStatus',
        ),
    ]
