# Generated by Django 2.2.24 on 2021-10-14 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0148_auto_20211013_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curationassociation',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curation_associations', to='api.Disease'),
        ),
    ]
