# Generated by Django 2.2.24 on 2021-10-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0148_auto_20211013_1436'),
        ('api', '0137_auto_20210806_1438'),
    ]

    operations = [
    ]
