# Generated by Django 2.2.24 on 2021-10-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0149_auto_20211014_0209'),
        ('api', '0137_auto_20210806_1037'),
    ]

    operations = [
    ]
