# Generated by Django 2.2.24 on 2021-10-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0152_auto_20211018_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvariantinsvip',
            name='summary_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='variantinsvip',
            name='summary_date',
            field=models.DateTimeField(null=True),
        ),
    ]
