# Generated by Django 2.2.24 on 2021-10-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0153_auto_20211019_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='summary_date',
            field=models.DateTimeField(null=True),
        ),
    ]
