# Generated by Django 2.2.24 on 2021-10-20 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0154_gene_summary_date'),
        ('api', '0150_merge_20211015_1250'),
    ]

    operations = [
    ]
