# Generated by Django 2.2.24 on 2021-11-03 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0155_merge_20211020_0106'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diseaseinsvip',
            unique_together=set(),
        ),
    ]
