# Generated by Django 2.2.24 on 2021-11-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0156_auto_20211103_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icdotopoapidisease',
            options={'managed': True},
        ),
    ]
