# Generated by Django 2.2.24 on 2022-01-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0159_auto_20220106_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='curationentry',
            name='escat_score',
            field=models.TextField(blank=True, null=True, verbose_name='ESCAT score'),
        ),
        migrations.AddField(
            model_name='historicalcurationentry',
            name='escat_score',
            field=models.TextField(blank=True, null=True, verbose_name='ESCAT score'),
        ),
    ]
