# Generated by Django 2.2.24 on 2022-02-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0160_auto_20220120_1322'),
        ('api', '0159_auto_20220106_0751'),
    ]

    operations = [
    ]
