# Generated by Django 2.2.28 on 2022-08-10 15:11

from django.db import migrations, models
import django_db_cascade.deletions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0160_auto_20220120_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curationentry',
            name='variant',
            field=models.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, related_name='curation_entries', to='api.Variant'),
        ),
    ]
