# Generated by Django 2.2.28 on 2022-08-12 13:39

from django.db import migrations, models
import django_db_cascade.deletions
import django_db_cascade.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0161_merge_20220203_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curationevidence',
            name='association',
        ),
        migrations.RemoveField(
            model_name='curationentry',
            name='curation_evidences',
        ),
        migrations.RemoveField(
            model_name='curationreview',
            name='curation_evidence',
        ),
        migrations.RemoveField(
            model_name='revisedreview',
            name='curation_evidence',
        ),
        migrations.AddField(
            model_name='revisedreview',
            name='curation_entry',
            field=django_db_cascade.fields.ForeignKey(null=True, on_delete=django_db_cascade.deletions.DB_CASCADE, related_name='revised_reviews', to='api.CurationEntry'),
        ),
        migrations.AlterField(
            model_name='curationentry',
            name='variant',
            field=models.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, related_name='curation_entries', to='api.Variant'),
        ),
        migrations.AlterField(
            model_name='curationreview',
            name='curation_entry',
            field=django_db_cascade.fields.ForeignKey(null=True, on_delete=django_db_cascade.deletions.DB_CASCADE, related_name='curation_reviews', to='api.CurationEntry'),
        ),
        migrations.DeleteModel(
            name='CurationAssociation',
        ),
        migrations.DeleteModel(
            name='CurationEvidence',
        ),
    ]
