# Generated by Django 2.2.28 on 2022-08-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0161_auto_20220810_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curationentry',
            name='status',
            field=models.TextField(choices=[('__module__', 'api.models.svip'), ('draft', 'draft'), ('saved', 'saved'), ('submitted', 'submitted'), ('unreviewed', 'unreviewed'), ('reviewed', 'reviewed'), ('__doc__', None)], db_index=True, default='draft', verbose_name='Curation Status'),
        ),
        migrations.AlterField(
            model_name='historicalcurationentry',
            name='status',
            field=models.TextField(choices=[('__module__', 'api.models.svip'), ('draft', 'draft'), ('saved', 'saved'), ('submitted', 'submitted'), ('unreviewed', 'unreviewed'), ('reviewed', 'reviewed'), ('__doc__', None)], db_index=True, default='draft', verbose_name='Curation Status'),
        ),
    ]
