# Generated by Django 2.2.28 on 2022-08-10 16:09

from django.db import migrations, models
import django_db_cascade.deletions
import django_db_cascade.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0162_auto_20220810_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curationreview',
            name='curation_entry',
            field=django_db_cascade.fields.ForeignKey(null=True, on_delete=django_db_cascade.deletions.DB_CASCADE, related_name='curation_reviews', to='api.CurationEntry'),
        ),
        migrations.AlterField(
            model_name='curationreview',
            name='status',
            field=models.TextField(choices=[('__module__', 'api.models.svip'), ('pending', 'pending'), ('rejected', 'rejected'), ('accepted', 'accepted'), ('__doc__', None)], db_index=True, default='pending', verbose_name='Review Status'),
        ),
    ]
