# Generated by Django 2.2.28 on 2022-08-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0163_auto_20220818_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curationreview',
            name='curation_entry',
        ),
        migrations.AlterField(
            model_name='curationentry',
            name='status',
            field=models.TextField(choices=[('draft', 'draft'), ('saved', 'saved'), ('ready_for_submission', 'ready_for_submission'), ('submitted', 'submitted'), ('unreviewed', 'unreviewed'), ('reviewed', 'reviewed')], db_index=True, default='draft', verbose_name='Curation Status'),
        ),
        migrations.AlterField(
            model_name='historicalcurationentry',
            name='status',
            field=models.TextField(choices=[('draft', 'draft'), ('saved', 'saved'), ('ready_for_submission', 'ready_for_submission'), ('submitted', 'submitted'), ('unreviewed', 'unreviewed'), ('reviewed', 'reviewed')], db_index=True, default='draft', verbose_name='Curation Status'),
        ),
    ]
