# Generated by Django 2.2.28 on 2022-08-18 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0163_auto_20220817_0853'),
    ]

    operations = [

        migrations.AlterField(
            model_name='submissionentry',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Disease'),
        ),
    ]
