# Generated by Django 2.2.28 on 2022-08-12 06:33

from django.db import migrations
import django_db_cascade.deletions
import django_db_cascade.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0163_auto_20220810_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curationreview',
            name='curation_evidence',
            field=django_db_cascade.fields.ForeignKey(null=True, on_delete=django_db_cascade.deletions.DB_CASCADE, related_name='curation_reviews', to='api.CurationEvidence'),
        ),
    ]
