# Generated by Django 2.2.28 on 2022-08-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0161_merge_20220203_0937'),
        ('api', '0164_auto_20220812_0633'),
    ]

    operations = [
    ]
