# Generated by Django 2.2.28 on 2022-08-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0164_auto_20220823_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curationreview',
            name='status',
        ),
        migrations.AddField(
            model_name='curationreview',
            name='acceptance',
            field=models.BooleanField(default=True),
        ),
    ]
