# Generated by Django 2.2.28 on 2022-08-12 14:25

from django.db import migrations, models
import django.db.models.deletion
import django_db_cascade.deletions
import django_db_cascade.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0165_merge_20220812_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curationevidence',
            name='association',
        ),
        migrations.RemoveField(
            model_name='sibannotation1',
            name='evidence',
        ),
        migrations.RemoveField(
            model_name='sibannotation2',
            name='evidence',
        ),
        migrations.RemoveField(
            model_name='curationentry',
            name='curation_evidences',
        ),
        migrations.RemoveField(
            model_name='curationreview',
            name='curation_evidence',
        ),
        migrations.RemoveField(
            model_name='revisedreview',
            name='curation_evidence',
        ),
        migrations.AddField(
            model_name='revisedreview',
            name='curation_entry',
            field=django_db_cascade.fields.ForeignKey(null=True, on_delete=django_db_cascade.deletions.DB_CASCADE, related_name='revised_reviews', to='api.CurationEntry'),
        ),
        migrations.AlterField(
            model_name='curationentry',
            name='status',
            field=models.TextField(choices=[('draft', 'draft'), ('saved', 'saved'), ('submitted', 'submitted'), ('unreviewed', 'unreviewed'), ('reviewed', 'reviewed')], db_index=True, default='draft', verbose_name='Curation Status'),
        ),
        migrations.AlterField(
            model_name='curationrequest',
            name='disease',
            field=django_db_cascade.fields.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, related_name='curation_requests', to='api.Disease'),
        ),
        migrations.AlterField(
            model_name='curationrequest',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curation_requests', to='api.Variant'),
        ),
        migrations.AlterField(
            model_name='curationreview',
            name='status',
            field=models.TextField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('accepted', 'accepted')], db_index=True, default='pending', verbose_name='Review Status'),
        ),
        migrations.AlterField(
            model_name='historicalcurationentry',
            name='status',
            field=models.TextField(choices=[('draft', 'draft'), ('saved', 'saved'), ('submitted', 'submitted'), ('unreviewed', 'unreviewed'), ('reviewed', 'reviewed')], db_index=True, default='draft', verbose_name='Curation Status'),
        ),
        migrations.DeleteModel(
            name='CurationAssociation',
        ),
        migrations.DeleteModel(
            name='CurationEvidence',
        ),
        migrations.DeleteModel(
            name='SIBAnnotation1',
        ),
        migrations.DeleteModel(
            name='SIBAnnotation2',
        ),
    ]
