# Generated by Django 2.2.28 on 2022-09-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0166_auto_20220902_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionentry',
            name='review_cycle',
            field=models.IntegerField(default=1),
        ),
    ]
