# Generated by Django 2.2.28 on 2022-12-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0167_submissionentry_review_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionentry',
            name='if_conflicting_reviews',
            field=models.BooleanField(default=False),
        ),
    ]
