# Generated by Django 2.2.28 on 2022-12-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0168_submissionentry_if_conflicting_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionentry',
            name='if_conflicting_reviews',
        ),
    ]
