# Generated by Django 2.2.28 on 2022-12-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0169_remove_submissionentry_if_conflicting_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionentry',
            name='if_conflicting_reviews',
            field=models.BooleanField(default=False),
        ),
    ]
